config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resource :accounts

  get "user/me", to: "users#me", as: "my_settings"
  patch "users/update_me", to: "users#update_me", as: "update_my_settings"
  get "user/password", to: "users#password", as: "my_password"
  patch "user/update_password", to: "users#update_password", as: "my_update_password"

  scope "account", as: "account" do
    resources :users
  end

  get "activity/mine"

  get "activity/feed"

  root to: "activity#mine"
end

app/models/account.rb
class Account < ApplicationRecord
  include Friendlyable
  resourcify
  has_many :users
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/friendlyable.rb
module Friendlyable
  extend ActiveSupport::Concern

  included do
    extend ::FriendlyId
    before_create :set_hash_id
    friendly_id :hash_id
  end

  def set_hash_id
    hash_id = nil
    loop do
      hash_id = SecureRandom.urlsafe_base64(9).gsub(/-|_/, ("a".."z")
      .to_a[rand(26)])
      break unless self.class.name.constantize.where(hash_id: hash_id).exists?
    end
    self.hash_id = hash_id
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  include Friendlyable
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :account, optional: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    redirect_to root_path unless current_user.account.nil?
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      current_user.account = @account
      current_user.add_role :admin, @account
      current_user.save
      redirect_to root_path, success: "Your account has been created!"
    else
      render :new
    end
  end

  private

  def account_params
    params.require(:account).permit(:name, :addr1, :addr2, :city, :state,
                                    :zip, :country)
  end
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  def mine
  end

  def feed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  layout :layout_by_resource

  helper_method :current_account

  def current_account
    @current_account ||= current_user.account
    @current_account
  end

  protected

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_up_path_for(_resource)
    new_accounts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :set_users, only: [:index]

  def index
  end

  def new
    @user = User.new
    set_choices
  end

  def edit
    set_choices
  end

  def me
    @user = current_user
  end

  def password
    @user = current_user
  end

  def update_password
    @user = current_user
    respond_to do |format|
      if @user.update(user_password_params)
        bypass_sign_in(@user)
        format.html { redirect_to my_password_path, notice: "Password was successfully updated." }
      else
        format.html { render :password }
      end
    end
  end

  def update_me
    @user = current_user
    respond_to do |format|
      if @user.update(user_params)
        format.html do
          redirect_to my_settings_path,
                      notice: "Your information was successfully updated."
        end
      else
        format.html { render :me }
      end
    end
  end

  def create
    @user = User.unscoped.new(user_params.except("role"))
    @user.account = current_account
    @user.password = "password123"

    respond_to do |format|
      begin
        if @user.valid? && @user.invite!(current_user)
          @user.add_role user_params[:role].to_sym, current_account
          format.html do
            redirect_to account_users_path,
                        notice: "User was successfully invited."
          end
        else
          set_choices
          format.html { render :new }
        end
      rescue ActiveRecord::RecordNotUnique
        flash[:alert] = "Email must be unique"
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params.except("role"))
        format.html do
          redirect_to account_users_path,
                      notice: "User was successfully updated."
        end
      else
        set_choices
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html do
        redirect_to account_users_path,
                    notice: "User was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_users
    @users = current_account.users
  end

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def set_choices
    @choices = []
    @choices << %w[Admin admin]
    @choices << %w[User user]
  end

  def user_params
    params.require(:user).permit(:name, :email, :role, :time_zone)
  end

  def user_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(_opts={})
    # return if flash[0][0] == :form_error
    flash.each do |msg_type, message|
      next if msg_type == :form_error
      concat(content_tag(:div, message.html_safe,
                         class: "alert #{bootstrap_class_for(msg_type)} fade in") do
               concat content_tag(:button, "x", class: "close", data: {
                                    dismiss: "alert"
                                  })
               concat message.html_safe
             end)
    end
    nil
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }
                       .join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block alert-fixed">
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/new.slim
.row
  .col-lg-12
    .box
      .box-header
        h2
          | New Account Information
      .box-body
        = form_for @account, html:{class: 'form-horizontal'} do |f|
          - if @account.errors.any?
            .alert.alert-error.alert-block.alert-fixed
              h4= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
              == @account.errors.full_messages.map{|msg|content_tag(:li, msg)}.join
          .form-group
            = f.label :name, class: 'control-label col-lg-2'
            .col-lg-10
              = f.text_field :name, placeholder: 'Enter your Account\'s Name', class: 'form-control'

          .form-group
            .col-lg-offset-2.col-lg-10
              = f.submit "Save", class: 'btn btn-primary'

app/views/activity/feed.html.slim
h1 Activity#feed
p Find me in app/views/activity/feed.html.slim

app/views/activity/mine.html.slim
h1 Activity#mine
p Find me in app/views/activity/mine.html.slim

app/views/layouts/application.slim
doctype HTML
HTML
  head
    title Standup App
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all',\
     'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag href=\
    "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/\
    font-awesome.min.css"

  body.fixed.skin-blue-light
    .wrapper
      = render 'layouts/navigation/layout'
      .content-wrapper
        = flash_messages
        .content
          = yield
      = render 'layouts/navigation/footer'

app/views/layouts/devise.slim
doctype html
html
  head
    title Standup App
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all',\
    'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application',\
    'data-turbolinks-track': 'reload'
    = stylesheet_link_tag href=\
    "//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css"
  body.login-page
    = flash_messages
    = yield

app/views/layouts/navigation/_footer.slim
footer.main-footer
  .pull-right.hidden-xs
    | Anything you want
  strong
    | Copyright © 2016
    a href="#"  Company
  | All rights reserved.

app/views/layouts/navigation/_header.slim
header.main-header
  a.logo href="/"
    | Standup App
  /! Header Navbar: style can be found in header.less
  nav.navbar.navbar-static-top role="navigation"
    /! Navbar Right Menu
    .navbar-custom-menu
      ul.nav.navbar-nav
        /! Messages: style can be found in dropdown.less
        li.dropdown.messages-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            i.fa.fa-envelope-o
            span.label.label-success 4
          ul.dropdown-menu
            li.header You have 4 messages
            li
              /! inner menu: contains the actual data
              ul.menu
                li
                  /! start message
                  a href="#"
                  .pull-left
                    img.img-circle alt=("User Image") src="http://placehold.it/160x160" /
                  h4
                    | Sender Name
                    small
                      i.fa.fa-clock-o
                      | 5 mins
                  p Message Excerpt
                /! end message
                | \...
            li.footer
              a href="#"  See All Messages
        /! Notifications: style can be found in dropdown.less
        li.dropdown.notifications-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            i.fa.fa-bell-o
            span.label.label-warning 10
          ul.dropdown-menu
            li.header You have 10 notifications
            li
              /! inner menu: contains the actual data
              ul.menu
                li
                  a href="#"
                    i.ion.ion-ios-people.info
                    | Notification title
                | \...
            li.footer
              a href="#"  View all
        /! Tasks: style can be found in dropdown.less
        li.dropdown.tasks-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            i.fa.fa-flag-o
            span.label.label-danger 9
          ul.dropdown-menu
            li.header You have 9 tasks
            li
              /! inner menu: contains the actual data
              ul.menu
                li
                  /! Task item
                  a href="#"
                  h3
                    | Design some buttons
                    small.pull-right 20%
                  .progress.xs
                    .progress-bar.progress-bar-aqua aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" role="progressbar" style=("width: 20%")
                      span.sr-only 20% Complete
                /! end task item
                | \...
            li.footer
              a href="#"  View all tasks
        /! User Account: style can be found in dropdown.less
        li.dropdown.user.user-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            img.user-image alt=("User Image") src="http://placehold.it/160x160" /
            span.hidden-xs Rodney Cullen
          ul.dropdown-menu
            /! User image
            li.user-header
              img.img-circle alt=("User Image") src="http://placehold.it/160x160" /
              p
                | Rodney Cullen - Web Developer
                small Member since Nov. 2012
            /! Menu Body
            li.user-body
              .col-xs-4.text-center
                a href="#"  Followers
              .col-xs-4.text-center
                a href="#"  Sales
              .col-xs-4.text-center
                a href="#"  Friends
            /! Menu Footer
            li.user-footer
              .pull-left
                a.btn.btn-default.btn-flat href="#"  Profile
              .pull-right
                a.btn.btn-default.btn-flat href="#"  Sign out

app/views/layouts/navigation/_layout.slim
= render "layouts/navigation/header"
= render "layouts/navigation/sidebar"

app/views/layouts/navigation/_sidebar.slim
.main-sidebar
  .sidebar
    .user-panel
      .pull-left.image
        img.img-circle alt=("User Image") src="http://placehold.it/160x160" /
      .pull-left.info
        p rodcul
        a href="#"
          i.fa.fa-circle.text-success
          | Online
    form.sidebar-form action="#" method="get"
      .input-group
        input.form-control name="q" placeholder="Search..." type="text" /
        span.input-group-btn
          button#search-btn.btn.btn-flat name="search" type="submit"
            i.fa.fa-search
    ul.sidebar-menu
      li.header HEADER
      li.active
        a href="#"
          span Link

      li
        a href="#"
          span Another Link
      li.treeview
        a href="#"
          span Multilevel
          i.fa.fa-angle-left.pull-right
        ul.treeview-menu
          li
            a href="#"  Link in level 2
          li
            a href="#"  Link in level 2

app/views/users/create.html.slim
h1 Users#create
p Find me in app/views/users/create.html.slim

app/views/users/edit.html.slim
.content-header
  h2 Users
.content
  .row
    .col-lg-12
        .box.box-primary
          = form_for(@user, url: account_user_path(@user), html: {class: 'form-horizontal'}) do |f|
            .box-header
              h3.box-title
                | Edit User Information
            .box-body
              -if @user.errors.any?
                .alert.alert-error.alert-block.alert-fixed
                  h4= "#{pluralize(@user.errors.count, "error")} prohibited the user from being saved:"
                  == @user.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
              .form-group
                = f.label :name, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.text_field :name, {placeholder: "Name", autofocus: true, class: "form-control"}
              .form-group
                = f.label :email, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.email_field :email, {placeholder: "Email Address", autofocus: true, class: "form-control"}
              .form-group
                = label_tag "user[role]", "Role", class: 'control-label col-lg-2'
                .col-lg-10
                  = select_tag "user[role]", options_for_select(@choices, @user.roles.first.name), class: 'form-control'
            .box-footer style="height: 55px;"
              span.pull-right
                = f.submit "Edit User", class: "btn btn-primary"

app/views/users/index.html.slim
.content-header
  h2 Users
.content
  .row
    .col-lg-12
      .box.box-primary
        .box-header
          h3.box-title
            = "Users in #{current_account.name}"
        .box-body
          .table-responsive
            table.table.table-striped
              thead
                tr
                  th Name
                  th Email
                  th Status
                  th Role
                  th Added at
                  th
              tbody
                - @users.each do |user|
                  tr
                    td= user.name
                    td= user.email
                    td= user.accepted_or_not_invited? ? "Active" : "Invited"
                    td= user.account.roles&.first&.name&.capitalize
                    td= user.created_at.strftime('%D')
                    td
                      = link_to 'Edit', edit_account_user_path(user),\
                      class: 'btn btn-default btn-xs'
                      = link_to 'Destroy', account_user_path(user),\
                      {method: :delete, data: { confirm: 'Are you sure?' },\
                      class: 'btn btn-warning btn-xs'} unless user.id == current_user.id

        .box-footer style="height: 55px;"
          span.pull-right
            a.btn.btn-primary href="#{new_account_user_path}"
              | Add User

app/views/users/me.slim
.content-header
  h2 Settings
.content
  .row
    .col-lg-12
        .box.box-primary
          = form_for(@user, url: update_my_settings_path, html:{class: 'form-horizontal'}) do |f|
            .box-header
              h3.box-title My Information
            .box-body
              -if @user.errors.any?
                .alert.alert-error.alert-block.alert-fixed
                  h4= "#{pluralize(@user.errors.count, "error")} prohibited your information from being saved:"
                  == @user.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
              .form-group
                = f.label :name, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.text_field :name, {placeholder: "Name", autofocus: true, class: "form-control"}
              .form-group
                = f.label :email, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.email_field :email, {placeholder: "Email Address", autofocus: true, class: "form-control"}
              .form-group
                = f.label :time_zone, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.time_zone_select(:time_zone, ActiveSupport::TimeZone.us_zones, {}, {class: 'form-control'})
            .box-footer
              .pull-right
                = f.submit "Update My Settings", class: "btn btn-primary"

app/views/users/new.html.slim
.content-header
  h2 Users
.content
  .row
    .col-lg-12
      .box.box-primary
        = form_for(@user, url: account_users_path, html: {class: 'form-horizontal'}) do |f|
          .box-header
            h3.box-title New User Information
          .box-body
              -if @user.errors.any?
                .alert.alert-error.alert-block.alert-fixed
                  h4= "#{pluralize(@user.errors.count, "error")} prohibited your the user from being saved:"
                  == @user.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
              .form-group
                = label_tag "user[name]", "Name", class: 'control-label col-lg-2'
                .col-lg-10
                  = f.text_field :name, {placeholder: "Name", autofocus: true, class: "form-control"}
              .form-group
                = label_tag "user[email]", "Email", class: 'control-label col-lg-2'
                .col-lg-10
                  = f.email_field :email, {placeholder: "Email Address", autofocus: true, class: "form-control"}
              .form-group
                = label_tag "user[role]", "Role", class: 'control-label col-lg-2'
                .col-lg-10
                  = select_tag "user[role]", options_for_select(@choices, 'user'), class: 'form-control'
          .box-footer style="height: 55px;"
            span.pull-right
              = f.submit "Add User", class: "btn btn-primary"

app/views/users/password.slim
.content-header
  h2 Settings
.content
  .row
    .col-lg-12
        .box.box-primary
           = form_for(@user, url: my_update_password_path, html:{class: 'form-horizontal'}) do |f|
            .box-header
              h3.box-title Update Password
            .box-body
              -if @user.errors.any?
                .alert.alert-error.alert-block.alert-fixed
                  h4= "#{pluralize(@user.errors.count, "error")} prohibited your information from being saved:"
                  == @user.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
              .form-group
                = f.label :password, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.password_field :password, {placeholder: "Enter New Password", autofocus: true, class: "form-control"}
              .form-group
                = f.label :password_confirmation, class: 'control-label col-lg-2'
                .col-lg-10
                  = f.password_field :password_confirmation, {placeholder: "Re-enter New Password", autofocus: true, class: "form-control"}
            .box-footer
              .pull-right
                = f.submit "Update My Password", class: "btn btn-primary"

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim

app/views/users/update.html.slim
h1 Users#update
p Find me in app/views/users/update.html.slim